using System.Security.Cryptography;
using System.Text;
using Pz.Cli;
using Pz.DuckDb;

namespace Pz.EndToEnd.Tests;

/// <summary>End-to-end: `pz run` moves data through the parquet source's
/// native <c>read_parquet</c> scan (no CSV anywhere in this fixture) -- LocalFiles parquet source ->
/// DuckDB staging -> SQL transform -> LocalFiles CSV sink. The seed parquet file is generated by DuckDB
/// at test time (not checked into the fixture tree, unlike the CSV fixtures) so this stays a plain-text
/// fixture directory like every other one under Fixtures/.</summary>
[Collection("console-redirection")]
public sealed class ParquetSourceE2ETests : IDisposable
{
    private readonly string _work = Path.Combine(Path.GetTempPath(), "pz-e2e-tests", Guid.NewGuid().ToString("N"));

    public ParquetSourceE2ETests() => CopyTree(Path.Combine(AppContext.BaseDirectory, "Fixtures", "parquet-to-csv"), _work);

    public void Dispose()
    {
        try { Directory.Delete(_work, recursive: true); } catch { /* best-effort cleanup */ }
    }

    [Fact]
    public async Task Parquet_to_transform_to_csv_roundtrips()
    {
        await SeedParquetAsync(Path.Combine(_work, "data", "orders.parquet"));

        var exit = CliApp.Build().Parse(["run", "--project", _work]).Invoke();
        Assert.Equal(ExitCodes.Ok, exit);

        var csvPath = Path.Combine(_work, "out", "customer_totals.csv");
        Assert.True(File.Exists(csvPath));

        var actual = await File.ReadAllTextAsync(csvPath);

        // Oracle, computed independently from the seed values below (not from the pipeline under
        // test): alice = rows 1,3,6,9 (10.25+30.75+25.00+25.00=91.00), bob = rows 2,5,8
        // (20.50+15.25+45.25=81.00), carol = rows 4,7,10 (5.00+35.50+65.00=105.50). DuckDB infers a
        // DECIMAL(_,2) type for the "amount" literals (not DOUBLE), so sum(amount) stays exact and
        // CsvSinkWriteSession's Decimal128Array formatting keeps the fixed 2-decimal scale.
        var oracle = "customer,orders,total\n" +
                     "alice,4,91.00\n" +
                     "bob,3,81.00\n" +
                     "carol,3,105.50\n";

        Assert.Equal(Digest(oracle), Digest(actual));
    }

    private static async Task SeedParquetAsync(string parquetPath)
    {
        Directory.CreateDirectory(Path.GetDirectoryName(parquetPath)!);
        var quoted = parquetPath.Replace("'", "''");

        await using var duck = DuckSession.Open(Path.Combine(Path.GetTempPath(), $"pz-e2e-seed-{Guid.NewGuid():N}.duckdb"));
        await duck.ExecuteAsync($"""
            copy (
                select * from (
                    values
                        (1, 'alice', 10.25),
                        (2, 'bob', 20.50),
                        (3, 'alice', 30.75),
                        (4, 'carol', 5.00),
                        (5, 'bob', 15.25),
                        (6, 'alice', 25.00),
                        (7, 'carol', 35.50),
                        (8, 'bob', 45.25),
                        (9, 'alice', 25.00),
                        (10, 'carol', 65.00)
                ) t(id, customer, amount)
            )
            to '{quoted}' (format parquet)
            """);
    }

    private static string Digest(string content) =>
        Convert.ToHexStringLower(SHA256.HashData(Encoding.UTF8.GetBytes(content)));

    private static void CopyTree(string from, string to)
    {
        Directory.CreateDirectory(to);
        foreach (var file in Directory.EnumerateFiles(from, "*", SearchOption.AllDirectories))
        {
            var dest = Path.Combine(to, Path.GetRelativePath(from, file));
            Directory.CreateDirectory(Path.GetDirectoryName(dest)!);
            File.Copy(file, dest, overwrite: true);
        }
    }
}
