<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.4" />
    <PackageReference Include="JsonSchema.Net" Version="9.2.2" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageReference Include="Parquet.Net" Version="6.0.3" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.4" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\connectors\Pz.Connector.LocalFiles\Pz.Connector.LocalFiles.csproj" />
    <ProjectReference Include="..\..\src\Pz.Connectors.TestKit\Pz.Connectors.TestKit.csproj" />
    <ProjectReference Include="..\..\src\Pz.Connectors.Toolkit\Pz.Connectors.Toolkit.csproj" />
    <ProjectReference Include="..\..\src\Pz.DuckDb\Pz.DuckDb.csproj" />
    <ProjectReference Include="..\..\src\Pz.Engine\Pz.Engine.csproj" />
  </ItemGroup>

</Project>
